// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FewtaZ0uJe3QWQ3Gr0PW_HgUIMn14nI',
    appId: '1:18912175:web:e77e4f3938d395084e155a',
    messagingSenderId: '18912175',
    projectId: 'quero-cafe-cf3c3',
    authDomain: 'quero-cafe-cf3c3.firebaseapp.com',
    storageBucket: 'quero-cafe-cf3c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzJkfkQu3ZuC8zkZRIqGzR0G9aKWjBNw',
    appId: '1:18912175:android:6d920919d6c279684e155a',
    messagingSenderId: '18912175',
    projectId: 'quero-cafe-cf3c3',
    storageBucket: 'quero-cafe-cf3c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3bTFzmZG3wZieobJBXSB9fWgtcQhTHw',
    appId: '1:18912175:ios:66ac8967d27a7cb24e155a',
    messagingSenderId: '18912175',
    projectId: 'quero-cafe-cf3c3',
    storageBucket: 'quero-cafe-cf3c3.firebasestorage.app',
    iosBundleId: 'com.example.queroCafe',
  );
}
